[package]
name = "serco_derive"
version = "0.1.0"
authors = ["Mikko Rantanen <jubjub@jubjubnest.net>"]

[lib]
proc-macro = true

[dependencies]
syn = "0.12"
quote = "0.4"
serco-common = { version = "0.1", path = "../serco-common" }

